=== XuuRee/apk-AccountG/Evidence_prijmu_a_vydaju/evidence.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xsd:element name="evidence" type="evidenceType">
        <xsd:key name="yearKey">
            <xsd:selector xpath="year"/>
            <xsd:field xpath="@yid"/>
        </xsd:key>
    </xsd:element>
    
    <xsd:complexType name="evidenceType">
        <xsd:sequence>
            <xsd:element name="year" type="yearType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="yearType">
        <xsd:sequence>
            <xsd:element name="payment" type="paymentType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="yid" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>
    
    <xsd:complexType name="paymentType">
        <xsd:sequence>
            <xsd:element name="type" type="typeType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="date" type="xsd:date" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="info" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="ammount" type ="xsd:decimal" minOccurs="1" maxOccurs="1"/>           
        </xsd:sequence>
        <xsd:attribute name="pid" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>
    
    <xsd:simpleType name="typeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="income"/>
            <xsd:enumeration value="expence"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== XuuRee/apk-AccountG/Evidence_prijmu_a_vydaju/evidence.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><?xml-stylesheet href="evidence_transform.xsl" type="text/xsl" ?><evidence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="evidence.xsd">
   <year yid="2015"><payment pid="1"><type>income</type><date>2017-01-01</date><info>predal som ladvinu</info><ammount>6666</ammount></payment><payment pid="2"><type>income</type><date>2017-01-03</date><info>secko som prepil</info><ammount>6600</ammount></payment><payment pid="3"><type>income</type><date>2017-01-01</date><info>doktor: odisla mi druha ladvina</info><ammount>1000</ammount></payment><payment pid="4"><type>expence</type><date>2017-01-11</date><info>kupil som ladvinu z cierneho trhu</info><ammount>100000</ammount></payment></year></evidence>
